name: Jody Johnston
favicon: null
layout_spectrum: 0.99766
typography_spectrum: 0.6557524385862052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e0e0'
    - '#090a0c'
    - '#a19e97'
    - '#6e706d'
    - '#2d3c37'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
